/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  range?: number;
  featured?: boolean;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type BrandReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "brand";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  discount?: number;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  stock?: number;
  brand?: BrandReference;
  status?: "new" | "hot" | "sale";
  variant?: "gadget" | "appliances" | "refrigerators" | "others";
  isFeatured?: boolean;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Author
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Category
  | CategoryReference
  | BrandReference
  | Product
  | Brand
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries/query.ts
// Variable: BRANDS_QUERY
// Query: *[_type=='brand'] | order(name asc) {    ...,     image {      _key,      _type,      "url": asset->url,      "lqip": asset->metadata.lqip    },    }
export type BRANDS_QUERY_RESULT = Array<{
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image: {
    _key: null;
    _type: "image";
    url: string | null;
    lqip: string | null;
  } | null;
}>;

// Source: sanity/queries/query.ts
// Variable: PRODUCTS_BY_VARIANT_QUERY
// Query: *[_type == "product" && variant == $variant][0...$quantity]{    ...,    "categories": categories[]->title,     images[] {        _key,        _type,        "url": asset->url,        "lqip": asset->metadata.lqip    }}
export type PRODUCTS_BY_VARIANT_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images: Array<{
    _key: string;
    _type: "image";
    url: string | null;
    lqip: string | null;
  }> | null;
  description?: string;
  price?: number;
  discount?: number;
  categories: Array<string | null> | null;
  stock?: number;
  brand?: BrandReference;
  status?: "hot" | "new" | "sale";
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
}>;

// Source: sanity/queries/query.ts
// Variable: PRODUCTS_BY_FILTER_QUERY
// Query: *[_type == 'product'     && (!defined($selectedCategory) || references(*[_type == "category" && slug.current == $selectedCategory]._id))    && (!defined($selectedBrand) || references(*[_type == "brand" && slug.current == $selectedBrand]._id))    && price >= $minPrice && price <= $maxPrice]       | order(name asc) {            ...,            "categories": categories[]->title,            images[] {            _key,            _type,            "url": asset->url,            "lqip": asset->metadata.lqip        }     }
export type PRODUCTS_BY_FILTER_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images: Array<{
    _key: string;
    _type: "image";
    url: string | null;
    lqip: string | null;
  }> | null;
  description?: string;
  price?: number;
  discount?: number;
  categories: Array<string | null> | null;
  stock?: number;
  brand?: BrandReference;
  status?: "hot" | "new" | "sale";
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
}>;

// Source: sanity/queries/query.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && slug.current == $slug] | order(name asc) [0] {    ..., images[] {    _key,    _type,    "url": asset->url,    "lqip": asset->metadata.lqip    }  }
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images: Array<{
    _key: string;
    _type: "image";
    url: string | null;
    lqip: string | null;
  }> | null;
  description?: string;
  price?: number;
  discount?: number;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  stock?: number;
  brand?: BrandReference;
  status?: "hot" | "new" | "sale";
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
} | null;

// Source: sanity/queries/query.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == 'category'] | order(name asc) {    ...,    image {      _key,      _type,      "url": asset->url,      "lqip": asset->metadata.lqip    },    "productCount": count(*[_type == "product" && references(^._id)])}
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  range?: number;
  featured?: boolean;
  image: {
    _key: null;
    _type: "image";
    url: string | null;
    lqip: string | null;
  } | null;
  productCount: number;
}>;

// Source: sanity/queries/query.ts
// Variable: CATEGORIES_WITH_QUANTITY_QUERY
// Query: *[_type == 'category'][0...$quantity] | order(name asc) {    ...,    image {      _key,      _type,      "url": asset->url,      "lqip": asset->metadata.lqip    },    "productCount": count(*[_type == "product" && references(^._id)])}
export type CATEGORIES_WITH_QUANTITY_QUERY_RESULT = Array<{
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  range?: number;
  featured?: boolean;
  image: {
    _key: null;
    _type: "image";
    url: string | null;
    lqip: string | null;
  } | null;
  productCount: number;
}>;

// Source: sanity/queries/query.ts
// Variable: BRAND_QUERY
// Query: *[_type == "product" && slug.current == $slug]{  "brandName": brand->title  }
export type BRAND_QUERY_RESULT = Array<{
  brandName: string | null;
}>;

// Source: sanity/queries/query.ts
// Variable: MY_ORDERS_QUERY
// Query: *[_type == 'order' && clerkUserId == $userId] | order(orderData desc){...,products[]{  ...,product->}}
export type MY_ORDERS_QUERY_RESULT = Array<never>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type==\'brand\'] | order(name asc) {\n    ..., \n    image {\n      _key,\n      _type,\n      "url": asset->url,\n      "lqip": asset->metadata.lqip\n    },    \n}': BRANDS_QUERY_RESULT;
    '*[_type == "product" && variant == $variant][0...$quantity]{\n    ...,\n    "categories": categories[]->title, \n    images[] {\n        _key,\n        _type,\n        "url": asset->url,\n        "lqip": asset->metadata.lqip\n    }\n}': PRODUCTS_BY_VARIANT_QUERY_RESULT;
    '*[_type == \'product\' \n    && (!defined($selectedCategory) || references(*[_type == "category" && slug.current == $selectedCategory]._id))\n    && (!defined($selectedBrand) || references(*[_type == "brand" && slug.current == $selectedBrand]._id))\n    && price >= $minPrice && price <= $maxPrice] \n      | order(name asc) {\n            ...,\n            "categories": categories[]->title,\n            images[] {\n            _key,\n            _type,\n            "url": asset->url,\n            "lqip": asset->metadata.lqip\n        } \n    }': PRODUCTS_BY_FILTER_QUERY_RESULT;
    '*[_type == "product" && slug.current == $slug] | order(name asc) [0] {\n    ..., images[] {\n    _key,\n    _type,\n    "url": asset->url,\n    "lqip": asset->metadata.lqip\n    }\n  }': PRODUCT_BY_SLUG_QUERY_RESULT;
    '*[_type == \'category\'] | order(name asc) {\n    ...,\n    image {\n      _key,\n      _type,\n      "url": asset->url,\n      "lqip": asset->metadata.lqip\n    },\n    "productCount": count(*[_type == "product" && references(^._id)])\n}': CATEGORIES_QUERY_RESULT;
    '*[_type == \'category\'][0...$quantity] | order(name asc) {\n    ...,\n    image {\n      _key,\n      _type,\n      "url": asset->url,\n      "lqip": asset->metadata.lqip\n    },\n    "productCount": count(*[_type == "product" && references(^._id)])\n}': CATEGORIES_WITH_QUANTITY_QUERY_RESULT;
    '*[_type == "product" && slug.current == $slug]{\n  "brandName": brand->title\n  }': BRAND_QUERY_RESULT;
    "*[_type == 'order' && clerkUserId == $userId] | order(orderData desc){\n...,products[]{\n  ...,product->\n}\n}": MY_ORDERS_QUERY_RESULT;
  }
}
